name: mobile_system
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI Icons
  cupertino_icons: ^1.0.8
  
  # Image picker for camera and gallery access
  image_picker: ^1.1.2
  
  # File picker for document upload functionality  
  file_picker: ^8.1.2
  
  # Permission handler for camera and storage permissions
  permission_handler: ^11.3.1
  
  # Path provider for file system access
  path_provider: ^2.1.4
  
  # Local authentication for biometric login
  local_auth: ^2.3.0

  pin_code_fields: ^8.0.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true